### ISSUE TITLE
error during update (docker install)

### ISSUE THREAD

**Issue by yeKcim** [elabftw/elabctl#21]
My elabftw is down, here is the error I have during update:

```
# elabctl update     

      _          _     _____ _______        __
  ___| |    __ _| |__ |  ___|_   _\ \      / /
 / _ \ |   / _| | '_ \| |_    | |  \ \ /\ / / 
|  __/ |__| (_| | |_) |  _|   | |   \ V  V /  
 \___|_____\__,_|_.__/|_|     |_|    \_/\_/   
                                              

Using elabctl configuration file: using default values (no config file found)
Using elabftw configuration file: /etc/elabftw.yml
---------------------------------------------
Do you want to make a backup before updating? (y/N)

Pulling mysql ... done
Pulling web   ... done
Removing mysql ... done
Creating mysql ... 

ERROR: for mysql  a bytes-like object is required, not 'str'

ERROR: for mysql  a bytes-like object is required, not 'str'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 261, in _raise_for_status
    response.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.21/containers/94d139d8f91d1eabeafd8d316f4e279acff2b8293c2f6548eea35db5235da8e0/start

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/compose/service.py", line 625, in start_container
    container.start()
  File "/usr/lib/python3/dist-packages/compose/container.py", line 241, in start
    return self.client.start(self.id, **options)
  File "/usr/lib/python3/dist-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/docker/api/container.py", line 1095, in start
    self._raise_for_status(res)
  File "/usr/lib/python3/dist-packages/docker/api/client.py", line 263, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/lib/python3/dist-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 500 Server Error: Internal Server Error ("b'cgroups: cgroup mountpoint does not exist: unknown'")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 11, in <module>
    load_entry_point('docker-compose==1.25.0', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 72, in main
    command()
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 128, in perform_command
    handler(command, command_options)
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 1107, in up
    to_attach = up(False)
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 1088, in up
    return self.project.up(
  File "/usr/lib/python3/dist-packages/compose/project.py", line 565, in up
    results, errors = parallel.parallel_execute(
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 112, in parallel_execute
    raise error_to_reraise
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 210, in producer
    result = func(obj)
  File "/usr/lib/python3/dist-packages/compose/project.py", line 548, in do
    return service.execute_convergence_plan(
  File "/usr/lib/python3/dist-packages/compose/service.py", line 545, in execute_convergence_plan
    return self._execute_convergence_create(
  File "/usr/lib/python3/dist-packages/compose/service.py", line 460, in _execute_convergence_create
    containers, errors = parallel_execute(
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 112, in parallel_execute
    raise error_to_reraise
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 210, in producer
    result = func(obj)
  File "/usr/lib/python3/dist-packages/compose/service.py", line 465, in <lambda>
    lambda service_name: create_and_start(self, service_name.number),
  File "/usr/lib/python3/dist-packages/compose/service.py", line 457, in create_and_start
    self.start_container(container)
  File "/usr/lib/python3/dist-packages/compose/service.py", line 627, in start_container
    if "driver failed programming external connectivity" in ex.explanation:
TypeError: a bytes-like object is required, not 'str'
Your are now running the latest eLabFTW version.
Make sure to read the CHANGELOG!
=> https://github.com/elabftw/elabftw/releases/latest
```
Please, help

**Comment by yeKcim** [comment]
In fact, I’ve got the same error with "start" 😖.

Debian 5.10.46-4 (2021-08-03) x86_64 GNU/Linux

**Comment by NicolasCARPi** [comment]
Are you pulling from a local docker repo? It's an error 500 for `http+docker://localhost/v1.21/containers/`, nothing I can do to help you.

**Comment by yeKcim** [comment]
I followed https://doc.elabftw.net/install.html classic docker install and update since 2019, strange…

**Comment by NicolasCARPi** [comment]
Then it might be either a temporary docker hub failure (happens), or an issue with your system. Everything green here: https://status.docker.com/. Did you try to reboot / restart the docker service?

**Comment by yeKcim** [comment]
😖

```
docker run hello-world
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
b8dfde127a29: Pulling fs layer                                                                                                                           b8dfde127a29: Pull complete 
Digest: sha256:61bd3cb6014296e214ff4c6407a5a7e7092dfa8eefdbbec539e133e97f63e09f
Status: Downloaded newer image for hello-world:latest
docker: Error response from daemon: cgroups: cgroup mountpoint does not exist: unknown.
ERRO[0003] error waiting for container: context canceled
```
I am not very familiar with docker (only use it for elaftw), I investigate

**Comment by yeKcim** [comment]
I’ve restarted the vm, first reflex

**Comment by NicolasCARPi** [comment]
`docker info` ?

**Comment by NicolasCARPi** [comment]
..and other information related to the OS

**Comment by yeKcim** [comment]
docker info                :
```
Client:
 Debug Mode: false

Server:
 Containers: 3
  Running: 0
  Paused: 0
  Stopped: 3
 Images: 3
 Server Version: 19.03.15
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.10.0-8-amd64
 Operating System: Debian GNU/Linux 11 (bullseye)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 1.26GiB
 Name: elabdop.univ-rennes1.fr
 ID: FKNO:BZB5:4CV7:37KX:MUZS:WXI5:2M6B:C7SA:JMK6:ELNW:UKIG:22UR
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
WARNING: No kernel memory limit support
WARNING: No kernel memory TCP limit support
WARNING: No oom kill disable support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
WARNING: No cpu shares support
```

I think it’s related to https://github.com/docker/for-linux/issues/219

**Comment by NicolasCARPi** [comment]
Did you try this: https://github.com/docker/for-linux/issues/219#issuecomment-375160449 ?

**Comment by NicolasCARPi** [comment]
If you're in a VM, I personnally would make sure backups are working, nuke it and build a new one with a more recent version of docker (20.10 is the latest). That might mean of course a more modern OS as base.

**Comment by yeKcim** [comment]
In 2019, I’ve installed docker after a 
`sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"`

I’ve upgrade my debian few days ago so, updating this repo + some update/restart/… and I’ve got the last docker and a functional elabftw ! Thanks a lot
